import type { CustomThemeDefinition } from './custom-theme-loader';

export const BUNDLED_THEMES: readonly CustomThemeDefinition[] = [
  {
    name: 'super-kimi-neon-noir',
    displayName: 'Super Kimi Neon Noir',
    base: 'dark',
    colors: {
      primary: '#00D5FF',
      accent: '#B784FF',
      text: '#E6EDF3',
      textStrong: '#FFFFFF',
      textDim: '#9AA7B2',
      textMuted: '#6F7A86',
      border: '#334155',
      borderFocus: '#00D5FF',
      success: '#36D399',
      warning: '#F5C542',
      error: '#FF5C7A',
      diffAdded: '#36D399',
      diffRemoved: '#FF5C7A',
      diffAddedStrong: '#7AF0B4',
      diffRemovedStrong: '#FF91A6',
      diffGutter: '#738091',
      diffMeta: '#9AA7B2',
      roleUser: '#FFE082',
      shellMode: '#B784FF',
    },
  },
  {
    name: 'super-kimi-graphite',
    displayName: 'Super Kimi Graphite',
    base: 'dark',
    colors: {
      primary: '#7DD3FC',
      accent: '#2DD4BF',
      text: '#D8DEE9',
      textStrong: '#ECEFF4',
      textDim: '#9CA3AF',
      textMuted: '#707987',
      border: '#4B5563',
      borderFocus: '#FBBF24',
      success: '#86EFAC',
      warning: '#FBBF24',
      error: '#F87171',
      diffAdded: '#86EFAC',
      diffRemoved: '#F87171',
      diffAddedStrong: '#BBF7D0',
      diffRemovedStrong: '#FCA5A5',
      diffGutter: '#707987',
      diffMeta: '#9CA3AF',
      roleUser: '#FDE68A',
      shellMode: '#C084FC',
    },
  },
  {
    name: 'super-kimi-ember',
    displayName: 'Super Kimi Ember',
    base: 'dark',
    colors: {
      primary: '#FFB86C',
      accent: '#8BE9FD',
      text: '#F1E7DA',
      textStrong: '#FFF8EF',
      textDim: '#B7A99A',
      textMuted: '#827466',
      border: '#5D4B3A',
      borderFocus: '#FFB86C',
      success: '#7DDC8A',
      warning: '#FFD166',
      error: '#FF6B6B',
      diffAdded: '#7DDC8A',
      diffRemoved: '#FF6B6B',
      diffAddedStrong: '#B4F2B8',
      diffRemovedStrong: '#FFA0A0',
      diffGutter: '#827466',
      diffMeta: '#B7A99A',
      roleUser: '#FFD166',
      shellMode: '#D6A4FF',
    },
  },
  {
    name: 'super-kimi-daylight',
    displayName: 'Super Kimi Daylight',
    base: 'light',
    colors: {
      primary: '#075985',
      accent: '#0F766E',
      text: '#172033',
      textStrong: '#0B1020',
      textDim: '#46556A',
      textMuted: '#66758A',
      border: '#8A98AA',
      borderFocus: '#B45309',
      success: '#166534',
      warning: '#B45309',
      error: '#B42318',
      diffAdded: '#166534',
      diffRemoved: '#B42318',
      diffAddedStrong: '#14532D',
      diffRemovedStrong: '#991B1B',
      diffGutter: '#66758A',
      diffMeta: '#46556A',
      roleUser: '#92400E',
      shellMode: '#6D28D9',
    },
  },
];
